### ISSUE TITLE
Feature Request: Dynamic MetaTags

### ISSUE THREAD

**Issue by vanxh** [erlage/rad#1]
Add options to dynamically update meta tags

**Comment by erlage** [comment]
Hi @vanxh , I'm assuming issue is SEO related.

From what I know, search engines parses only static parts from a page, leaving scripts behind. Being a client side script, framework will not be executed at the time of crawl. Which means updating meta tags from framework side won't help crawler.

If you want to do that for some other reason or you've something else in mind, I'm open to discuss that.

**Comment by ambanikousik** [comment]
still meta tags are necessary when you share a link to any social media, meta tags help to generate custom thumbnail

**Comment by daniel-v** [comment]
FB/Meta does not execute JS when looking for its tags but others do eg. Google.

So in some sense, this is a request for SSR and in another sense, a way to manipulate stuff outside the "world of the application". 

What I mean by the "world of the app" is anything below the root of the topmost widget.
