### ISSUE TITLE
Support for static site generation

### ISSUE THREAD

**Issue by flexagoon** [erlage/rad#18]
I just tried this package and I love it! It seems like a great alternative to https://github.com/schultek/jaspr (both project have their pros and cons of course)

However, it would be great to have support for static site generation in Rad, to be able to generate static html pages from my dart code.

**Comment by erlage** [comment]
Thanks for trying it out, I'm glad that you liked it!

I think static site generation(SSG) is not very useful without the support for hydration(part of server side rendering).  

Both  SSG/SSR are undoubtedly complex and requires considerable amount of time, and I don't think I'm going to work on them soon. I could add a basic support for SSG/SSR and call it a day but I know that won't help and you'll eventually finds out why.
